### ISSUE TITLE
Regression about customView

### ISSUE THREAD

**Issue by marcoberetta96** [Ezaldeen99/material_dialogs#11]
The `customView` parameter was working in version `1.0.0`, but it's not working anymore in version `1.1.0`.
The custom view is simply not showed.

**Comment by Ezaldeen99** [comment]
I will check it and upload an update soon

**Comment by Ezaldeen99** [comment]
--fixed in `1.1.1`

**Comment by marcoberetta96** [comment]
Solved! Thank you!
