### ISSUE TITLE
animation error

### ISSUE THREAD

**Issue by akhilg-9** [Ezaldeen99/material_dialogs#17]
am getting an error while trying to use "animation: "

**Comment by Ezaldeen99** [comment]
please add the stack trace in order to investigate this issue

**Comment by faridistiqlal** [comment]
the name parameter 'animation' isn't defined

**Comment by Ezaldeen99** [comment]
as mentioned in the breakout changes, animation is not available anymore 


## [1.1.0]
## Breakout changes:
remove `animation`, `frameRate`, `reverse` and replace it with `lottieBuilder`

please refer to the example project to see an updated example 


I will close this currently, if you have any other questions please reopen this issue or open new issue

**Comment by faridistiqlal** [comment]
lottieBuilder: Lottie.asset(
          'assets/cong_example.json',
          fit: BoxFit.contain,
        ),

thanks. works
