### ISSUE TITLE
Is there a way to limit the width of the dialog?

### ISSUE THREAD

**Issue by 5stones1sling** [Ezaldeen99/material_dialogs#18]
I am displaying the dialog in a flutter web app, and the width of the dialog stretches from end to end. Is there a way to limit the width of the dialog
<img width="983" alt="Screen Shot 2022-05-21 at 7 33 59 PM" src="https://user-images.githubusercontent.com/2801856/169672245-b06f70e2-4cf3-44d6-b7dc-1ecefb4cccc4.png">
?

**Comment by Ezaldeen99** [comment]
thanks for reporting this issue, I will start working on finding a way to fix this

**Comment by Ezaldeen99** [comment]
Starting from `1.1.3` you can use `dialogWidth` to specify the width of the dialogue compared to the screen size. please refer to the example section for more.

I will close this for now, please open it again in case you had any issues with this update
<img width="1267" alt="Screen Shot 2022-05-23 at 3 10 47 PM" src="https://user-images.githubusercontent.com/30810111/169817604-e3de94b2-d95b-4dff-ac5f-ad979e1e7f88.png">

**Comment by 5stones1sling** [comment]
Thank you, works perfect.

Ezaldeen Sahb ***@***.***> 于 2022年5月23日周一 上午8:18写道：

**Comment by ChrisRPL** [comment]
For me setting dialogWidth for flutter web changes nothing.

**Comment by fujiser** [comment]
> For me setting dialogWidth for flutter web changes nothing.

Aren't you specifying a size for dialogWidth? Looking at the source, it seems you need to specify a ratio. For example: 0.5.

https://github.com/Ezaldeen99/material_dialogs/blob/master/lib/widgets/dialogs/dialog_widget.dart#L65
