### ISSUE TITLE
Method call null on bottomMaterialDialog

### ISSUE THREAD

**Issue by Ro-El** [Ezaldeen99/material_dialogs#3]
Hi,

Dialogs.materialDialog() works, but Dialogs.bottomMaterialDialog() doesn't.
It produces this stacktrace:

The following NoSuchMethodError was thrown building BottomSheet(dirty, dependencies: [_InheritedTheme, _LocalizationsScope-[GlobalKey#e7ba0]], state: _BottomSheetState#a43c6):
The method '>' was called on null.
Receiver: null
Tried calling: >(0)

The relevant error-causing widget was
MaterialApp
lib\main.dart:12
When the exception was thrown, this was the stack
#0      Object.noSuchMethod (dart:core-patch/object_patch.dart:51:5)
#1      new FrameRate
package:lottie/src/frame_rate.dart:7
#2      Dialogs.bottomMaterialDialog.<anonymous closure>
package:material_dialogs/material_dialogs.dart:111
#3      _BottomSheetState.build
package:flutter/…/material/bottom_sheet.dart:266
#4      StatefulElement.build
package:flutter/…/widgets/framework.dart:4744
...

Any help would be appreciated :)

Greetings,

R.

**Comment by Ezaldeen99** [comment]
Hi, thanks for reporting this issue, it seems that the null frame rate in the bottom navBar is causing this issue.

I just uploaded a new version, please update your package to 0.1.2, please update or specify a frame rate for your animations

**Comment by Ro-El** [comment]
Thank you for the quick fix! This solves the problem. What value do you suggest for the frame rate?

**Comment by Ezaldeen99** [comment]
you can set it in any value between 15-30, or leave it empty to have the default value

**Comment by Ro-El** [comment]
> you can set it in any value between 15-30, or leave it empty to have the default value

Thanks again!
