### ISSUE TITLE
BUG: bottomMaterialDialog -> actions field will not shown when keyboard is open

### ISSUE THREAD

**Issue by Deniz66** [Ezaldeen99/material_dialogs#36]
We have the problem that the action field that contains an cancel button is not displayed when the keyboard is up. 
A black field is displayed, which takes up a lot of space.

![image](https://github.com/user-attachments/assets/ff5b8203-2a48-4c0e-a5ed-022fdcaaac7b)

**Comment by Ezaldeen99** [comment]
In general it is not a good idea to put a text field inside your dialogs, however you might need to check the android configurations for your app. 

`android:windowSoftInputMode ` this will help you define how your activity react to input methods
