### ISSUE TITLE
Closing dialog programmatically

### ISSUE THREAD

**Issue by Ro-El** [Ezaldeen99/material_dialogs#4]
Hi,

Currently opening a materialDialog from a bottomMaterialDialog causes the bottomMaterialDialog to persist. Meaning that two taps are required to exit from both dialogs back to the main screen. 

Seems like a method to close a dialog programmatically would help circumvent this problem.

**Comment by Ezaldeen99** [comment]
Hi, I will start to work on such a feature to add it in the next release

**Comment by Ro-El** [comment]
> Hi, I will start to work on such a feature to add it in the next release 

You can achieve the desired effect by using navigator.pop(context) before calling the second dialog. Not sure if a more elegant solution is possible.

**Comment by Ezaldeen99** [comment]
great to know that you have it done

**Comment by akhilg-9** [comment]
@Ro-El can u explain properly once.
