### ISSUE TITLE
Stateful versions of dialogs

### ISSUE THREAD

**Issue by Ro-El** [Ezaldeen99/material_dialogs#5]
Hi,

Would it be possible to add stateful vesions of the dialogs?
Allowing to setState from one of the dialog buttons to for instance change the title or msg used for the dialog.

Greetings,

R.

**Comment by Ezaldeen99** [comment]
Hi,

Sure, working on it.

**Comment by Ezaldeen99** [comment]
I am afraid this won't be appliable soon. feel free to copy the material dialogs widget to your project, and change it to a stateful widget.

**Comment by marcoberetta96** [comment]
Is there any update on this?

**Comment by Ezaldeen99** [comment]
@marcoberetta96  a new update will be released on Friday hopefully
